- name: backup running config
  hosts: all
  connection: network_cli
  gather_facts: no

  tasks: 
    - name: gather hostname from device
      ios_facts:

    - name: retrieve running config
      ios_command: 
        commands: show running-config
      register: running_output

    - name: save running-config to file
      copy:
        content: "{{ running_output.stdout[0] }}"
        dest: "./backups/{{ ansible_net_hostname }}_running_config.cfg"
      delegate_to: localhost
