vlans:
  - id: 10
    name: CORE
  - id: 20
    name: MGMT
  - id: 30
    name: COMPUTE 
  - id: 99
    name: NATIVE
  - id: 100
    name: R&D
  - id: 200
    name: EMPLOYEE
  - id: 300
    name: GUEST
  - id: 999
    name: BLACKHOLE